version: '3.8'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - $POSTGRES_PORT
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      retries: 5
      interval: 5s
      timeout: 5s

  api:
    image: plamer88/digital_market:api-01
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - static_files:/digital_market/static
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: plamer88/digital_market:api-01
    env_file:
      - .env
    volumes:
      - static_files:/digital_market/static
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c './manage.py makemigrations && ./manage.py migrate'

  nginx:
    image: nginx:alpine

    depends_on:
      api:
        condition: service_started
    volumes:
      - static_files:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:3000'

volumes:
  postgres_data:
  static_files: