# Generated by Django 4.2.1 on 2023-06-01 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='contact',
            field=models.ManyToManyField(null=True, to='supplier.contact'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='debt',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='factory',
            name='product',
            field=models.ManyToManyField(null=True, to='supplier.product'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='contact',
            field=models.ManyToManyField(null=True, to='supplier.contact'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='debt',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='product',
            field=models.ManyToManyField(null=True, to='supplier.product'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='contact',
            field=models.ManyToManyField(null=True, to='supplier.contact'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='debt',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='product',
            field=models.ManyToManyField(null=True, to='supplier.product'),
        ),
    ]
